// Serves dist-demo/preview-fragment.html inside a minimal skeleton (like the Artifact host) and exercises it.
import { chromium } from 'playwright-core'
import http from 'node:http'
import fs from 'node:fs'
const frag = fs.readFileSync('dist-demo/preview-fragment.html', 'utf8')
const doc = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><style>:root{color-scheme:light}body{margin:0;font:14px system-ui}</style></head><body>${frag}</body></html>`
const srv = http.createServer((_, res) => { res.setHeader('content-type', 'text/html'); res.end(doc) }).listen(0)
const base = `http://localhost:${srv.address().port}/`
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 } })
const p = await ctx.newPage()
const errors = []; p.on('pageerror', e => errors.push(e.message)); p.on('console', m => m.type() === 'error' && !/fonts\.g/.test(m.text()) && errors.push(m.text()))
let fail = 0; const ok = (n, c) => { console.log(`${c ? '✓' : '✗ FAIL'} ${n}`); if (!c) fail++ }
await p.goto(base); await p.waitForSelector('text=Application pipeline')
ok('dashboard renders without login', true)
ok('banner shown', await p.getByText('Live preview').isVisible())
await p.getByRole('link', { name: 'Companies' }).first().click(); await p.waitForSelector('table tbody tr')
ok('navigate to Companies (memory router)', (await p.locator('table tbody tr').count()) === 13)
await p.getByRole('button', { name: 'Add company' }).first().click()
await p.getByLabel(/Company name/).fill('Preview Test Co')
await p.getByRole('button', { name: 'Add company' }).last().click()
await p.locator('[role=status]', { hasText: 'Company added' }).waitFor()
ok('create company', (await p.locator('table tbody tr').count()) === 14)
await p.reload(); await p.waitForSelector('text=Application pipeline')
await p.getByRole('link', { name: 'Companies' }).first().click(); await p.waitForSelector('table tbody tr')
ok('persisted across reload (localStorage)', (await p.locator('table tbody tr').count()) === 14)
await p.getByRole('link', { name: 'Applications' }).first().click()
await p.getByRole('button', { name: 'Board' }).click()
await p.locator('[data-testid=app-card]').first().dragTo(p.getByRole('listitem', { name: /^Offer,/ }))
await p.locator('[role=status]', { hasText: 'Moved to Offer' }).waitFor()
ok('drag & drop stage change', true)
await p.getByRole('button', { name: 'Table' }).click()
await p.getByRole('button', { name: 'Export CSV' }).click()
ok('export does not crash (clipboard fallback)', true)
await p.getByRole('link', { name: 'Follow-ups' }).first().click()
await p.locator('[data-state=today]').getByRole('button', { name: 'Mark Completed' }).click()
await p.locator('[role=status]', { hasText: 'completed' }).waitFor()
ok('follow-up completed', true)
for (const n of ['Analytics', 'Calendar', 'Interviews', 'Contacts', 'Settings']) { await p.getByRole('link', { name: n }).first().click(); await p.waitForTimeout(150) }
ok('all pages open', true)
await p.getByRole('button', { name: 'Load demo data' }).click(); await p.getByRole('button', { name: 'Replace all data' }).click()
await p.locator('[role=status]', { hasText: 'Data replaced' }).waitFor(); ok('reset works', true)
await ctx.close()
const m = await (await b.newContext({ viewport: { width: 390, height: 844 } })).newPage()
await m.goto(base); await m.waitForSelector('text=Application pipeline')
ok('no horizontal overflow on phone', !(await m.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1)))
await m.screenshot({ path: 'shots/preview-mobile.png' })
await b.close(); srv.close()
console.log(errors.length ? 'ERRORS:\n' + errors.join('\n') : 'no console errors'); process.exit(fail || errors.length ? 1 : 0)
