// End-to-end workflow checks. Run: BASE=http://localhost:3077 node e2e/workflows.mjs (needs a fresh, unconfigured server).
import { chromium } from 'playwright-core'
import fs from 'node:fs'
const base = process.env.BASE ?? 'http://localhost:3077'
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM ?? '/opt/pw-browsers/chromium' })
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, acceptDownloads: true })
const page = await ctx.newPage()
const errors = []
page.on('pageerror', e => errors.push('pageerror: ' + e.message))
page.on('console', m => { if (m.type() === 'error' && !/40[019]/.test(m.text())) errors.push('console: ' + m.text()) })
let pass = 0, fail = 0
const ok = (name, cond, extra = '') => { cond ? pass++ : fail++; console.log(`${cond ? '  ✓' : '  ✗ FAIL'} ${name}${cond ? '' : ' ' + extra}`) }
const go = async p => { await page.goto(base + p); await page.waitForLoadState('networkidle') }
const rowCount = () => page.locator('table tbody tr').count()
const toast = async text => { try { await page.locator('[role=status]', { hasText: text }).first().waitFor({ timeout: 3000 }); return true } catch { return false } }
const section = n => console.log(`\n${n}`)

section('Auth')
await go('/')
await page.getByLabel('Your name').fill('Mostafa Taha')
await page.getByLabel('Email').fill('me@example.com')
await page.getByLabel('Password').fill('short')
await page.getByRole('button', { name: 'Create account' }).click()
ok('weak password rejected with message', await page.getByText('Use at least 8 characters').first().isVisible())
await page.getByLabel('Password').fill('correct-horse-9')
await page.getByRole('button', { name: 'Create account' }).click() // default mode = my target offices
await page.waitForSelector('text=Application pipeline')
ok('account created, signed in', true)

section('Target list (33 offices from the user)')
await go('/companies')
ok('33 target companies loaded', (await rowCount()) === 33, String(await rowCount()))
ok('Arabic names render', await page.getByText('شركة الدرعية').first().isVisible())
await page.getByLabel('Search companies', { exact: true }).fill('omrania')
ok('search narrows to 1', (await rowCount()) === 1)
await page.getByLabel('Search companies', { exact: true }).fill('')

section('Switch to demo data via Settings')
await go('/settings')
await page.getByRole('button', { name: 'Load demo data' }).click()
await page.getByRole('button', { name: 'Replace all data' }).click()
ok('reset toast', await toast('Data replaced'))
await go('/companies')
ok('demo companies = 13', (await rowCount()) === 13, String(await rowCount()))

section('Companies CRUD')
await page.getByRole('button', { name: 'Add company' }).first().click()
await page.getByRole('button', { name: 'Add company' }).last().click()
ok('validation: name required', await page.getByText('Company name is required').isVisible())
await page.getByLabel(/Company name/).fill('Test Studio')
await page.getByLabel('Company type', { exact: true }).selectOption('Joinery')
await page.getByLabel('Location', { exact: true }).fill('Riyadh, KSA')
await page.getByLabel('Website', { exact: true }).fill('not a url')
await page.getByRole('button', { name: 'Add company' }).last().click()
ok('validation: bad url', await page.getByText('Enter a valid URL').first().isVisible())
await page.getByLabel('Website', { exact: true }).fill('teststudio.example.com')
await page.getByRole('button', { name: 'Add company' }).last().click()
ok('company added toast', await toast('Company added'))
ok('14 companies', (await rowCount()) === 14)
await page.getByLabel('Filter by company type').selectOption('Joinery')
ok('type filter works', (await rowCount()) === 2, String(await rowCount()))
await page.getByRole('button', { name: 'Clear' }).click()
await page.getByLabel('Search companies', { exact: true }).fill('test studio')
await page.getByRole('button', { name: 'Actions for Test Studio' }).click()
await page.getByRole('menuitem', { name: 'Edit' }).click()
await page.getByLabel('Industry', { exact: true }).fill('Millwork')
await page.getByRole('button', { name: 'Save changes' }).click()
ok('company updated', await toast('Company updated'))
await page.getByRole('button', { name: 'Actions for Test Studio' }).click()
await page.getByRole('menuitem', { name: 'Archive' }).click()
ok('archived hides row', (await page.locator('table tbody tr').count()) === 0 || await page.getByText('No companies match').isVisible())
await page.getByLabel(/Archived/).check()
ok('archived list shows it', await page.getByText('Test Studio').first().isVisible())
await page.getByRole('button', { name: 'Actions for Test Studio' }).click()
await page.getByRole('menuitem', { name: 'Delete' }).click()
await page.getByRole('button', { name: 'Cancel' }).click()
ok('cancel keeps it', await page.getByText('Test Studio').first().isVisible())
await page.getByRole('button', { name: 'Actions for Test Studio' }).click()
await page.getByRole('menuitem', { name: 'Delete' }).click()
await page.getByRole('button', { name: 'Delete', exact: true }).click()
ok('deleted toast', await toast('deleted'))
await go('/companies')
ok('delete persisted after reload (13)', (await rowCount()) === 13)
await page.getByRole('button', { name: /^Company/ }).click()
const first = await page.locator('table tbody tr').first().innerText()
await page.getByRole('button', { name: /^Company/ }).click()
const first2 = await page.locator('table tbody tr').first().innerText()
ok('sorting toggles order', first !== first2)
await page.getByRole('button', { name: 'Import' }).click()
await page.getByRole('textbox', { name: 'Companies' }).fill('New Office One\nNew Office Two\nAl Noor Architecture')
ok('import preview counts duplicates', await page.getByText(/1 already in your list/).isVisible())
await page.getByRole('button', { name: /Import 2 companies/ }).click()
ok('import toast', await toast('2 companies imported'))
const [dl] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: 'Export CSV' }).click()])
const csv = fs.readFileSync(await dl.path(), 'utf8')
ok('companies CSV export has header + rows', csv.includes('Company,Type') && csv.includes('New Office One'))

section('Company profile')
await go('/companies/co_alnoor')
ok('profile header + contacts + applications + timeline', await page.getByText('Ahmed Karim').first().isVisible() && await page.getByText('Senior Architect').first().isVisible() && await page.getByText('Activity timeline').isVisible())

section('Applications')
await go('/applications')
ok('15 applications', (await rowCount()) === 15)
await page.getByLabel('Filter by status').selectOption('Offer')
ok('status filter', (await rowCount()) === 1)
await page.getByRole('button', { name: 'Clear' }).click()
await page.getByLabel('Filter by priority').selectOption('High')
ok('priority filter', (await rowCount()) === 5, String(await rowCount()))
await page.getByRole('button', { name: 'Clear' }).click()
await page.getByLabel('Minimum salary').fill('25000')
ok('salary filter', (await rowCount()) > 0 && (await rowCount()) < 15, String(await rowCount()))
await page.getByRole('button', { name: 'Clear' }).click()
await page.getByLabel('Search applications', { exact: true }).fill('fit-out')
ok('search in positions', (await rowCount()) === 1)
await page.getByLabel('Search applications', { exact: true }).fill('')
await page.getByRole('button', { name: 'Add application' }).first().click()
await page.getByLabel(/^Company \*$/).selectOption('__new')
await page.getByLabel('New company name').fill('Inline Co')
await page.getByRole('button', { name: 'Add application' }).last().click()
ok('validation: position required', await page.getByText('Position is required').isVisible())
await page.getByLabel(/^Position/).fill('Site Architect')
await page.getByLabel('Salary min').fill('20000'); await page.getByLabel('Salary max').fill('10000')
await page.getByRole('button', { name: 'Add application' }).last().click()
ok('validation: max < min', await page.getByText('Max must be ≥ min').isVisible())
await page.getByLabel('Salary max').fill('30000')
await page.getByRole('button', { name: 'Add application' }).last().click()
ok('application added (+ follow-up)', await toast('follow-up scheduled'))
ok('16 applications', (await rowCount()) === 16)
await go('/companies')
await page.getByLabel('Search companies', { exact: true }).fill('inline co')
ok('inline company created', (await rowCount()) === 1)
await go('/applications')
await page.getByRole('button', { name: 'Board' }).click()
const card = page.locator('[data-testid=app-card]', { hasText: 'Site Architect' })
const target = page.getByRole('listitem', { name: /^Screening,/ })
await card.dragTo(target)
ok('drag to Screening → toast', await toast('Moved to Screening'))
ok('card now in Screening column', await target.getByText('Site Architect').isVisible())
await go('/applications')
await page.getByLabel('Search applications', { exact: true }).fill('Site Architect')
await page.getByText('Site Architect').first().click()
await page.waitForURL(/applications\//)
ok('stage persisted after reload', (await page.locator('#stage-select').inputValue()) === 'Screening')
await page.locator('#stage-select').selectOption('Offer')
ok('stage select → Offer', await toast('Moved to Offer'))
ok('timeline shows stage change', await page.getByText('Moved from Screening to Offer').isVisible())
await page.getByRole('button', { name: 'Add event' }).click()
await page.getByLabel('Event type', { exact: true }).selectOption('Phone call')
await page.getByLabel(/Description/).fill('Call with recruiter')
fs.writeFileSync('/tmp/att.txt', 'hello attachment')
await page.locator('input[type=file]').setInputFiles('/tmp/att.txt')
await page.getByRole('button', { name: 'Log activity' }).click()
ok('activity logged', await toast('Activity logged'))
ok('attachment link on timeline', await page.getByRole('link', { name: 'att.txt' }).isVisible())
const href = await page.getByRole('link', { name: 'att.txt' }).getAttribute('href')
const body = await page.evaluate(async h => (await fetch(h)).text(), href)
ok('attachment downloads intact', body === 'hello attachment', body)
await page.getByRole('button', { name: 'Delete' }).first().click()
await page.getByRole('button', { name: 'Delete', exact: true }).last().click()
await page.waitForURL(/\/applications$/)
await page.waitForSelector('table tbody tr')
ok('application deleted → back to list', (await rowCount()) === 15)
const [dl2] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: 'Export CSV' }).click()])
ok('applications CSV export', fs.readFileSync(await dl2.path(), 'utf8').includes('Salary min'))

section('Follow-ups')
await go('/follow-ups')
ok('overdue + today cards', (await page.locator('[data-state=overdue]').count()) === 2 && (await page.locator('[data-state=today]').count()) === 1)
ok('overdue warning wording', await page.getByText('FOLLOW UP TODAY').isVisible() && await page.getByText(/OVERDUE · 2 DAYS/).isVisible())
await page.locator('[data-state=today]').getByRole('button', { name: 'Mark Completed' }).click()
ok('mark completed toast', await toast('Follow-up marked as completed'))
ok('today card gone', (await page.locator('[data-state=today]').count()) === 0)
await page.locator('[data-state=overdue]').first().getByRole('button', { name: 'Reschedule' }).click()
await page.getByRole('button', { name: 'In 3 days' }).click()
await page.locator('dialog').getByRole('button', { name: 'Reschedule' }).click()
ok('reschedule toast', await toast('rescheduled'))
ok('one overdue left', (await page.locator('[data-state=overdue]').count()) === 1)
await page.getByRole('button', { name: 'Schedule follow-up' }).click()
await page.getByLabel('Application', { exact: true }).selectOption({ index: 2 })
await page.getByLabel('Due date').fill('2026-10-12')
await page.getByRole('button', { name: 'Schedule', exact: true }).click()
ok('follow-up scheduled', await toast('Follow-up scheduled'))
await go('/follow-ups')
await page.getByRole('tab', { name: /Completed/ }).click()
ok('completed tab lists completed', (await page.locator('[data-state=completed]').count()) >= 3)
await go('/')
ok('dashboard follow-ups KPI updated', await page.getByText('1 overdue').first().isVisible())

section('Interviews')
await go('/interviews')
const before = await page.locator('[data-testid=interview-card]').count()
await page.getByRole('button', { name: 'Schedule interview' }).first().click()
await page.getByLabel(/^Application/).selectOption({ index: 2 })
await page.getByLabel('Interview type', { exact: true }).selectOption('Portfolio Review')
await page.getByLabel(/^Date/).fill('2026-10-20'); await page.getByLabel('Time', { exact: true }).fill('15:30')
await page.getByLabel('Interviewer').fill('Jane Doe')
await page.getByLabel('Preparation notes').fill('Bring printed portfolio')
await page.getByRole('button', { name: 'Schedule', exact: true }).click()
ok('interview scheduled', await toast('Interview scheduled'))
ok('upcoming count +1', (await page.locator('[data-testid=interview-card]').count()) === before + 1)
await page.locator('[data-testid=interview-card]', { hasText: 'Jane Doe' }).getByRole('button', { name: 'Interview actions' }).click()
await page.getByRole('menuitem', { name: 'Mark passed' }).click()
ok('mark passed', await toast('marked passed'))
await page.getByRole('tab', { name: /Past/ }).click()
ok('passed interview moved to past with result', await page.locator('[data-testid=interview-card]', { hasText: 'Jane Doe' }).getByText('Result: Passed').isVisible())
await page.getByRole('button', { name: 'Calendar' }).click()
ok('interview calendar view renders', await page.getByRole('grid').isVisible())

section('Contacts')
await go('/contacts')
await page.getByRole('button', { name: 'Add contact' }).first().click()
await page.getByLabel(/^Name/).fill('Sara Test')
await page.getByLabel('Email', { exact: true }).fill('bad-email')
await page.getByLabel(/^Company \*$/).selectOption('')
await page.getByRole('button', { name: 'Add contact' }).last().click()
ok('validation: company required + email', await page.getByText('Choose a company').isVisible() && await page.getByText('Enter a valid email address').isVisible())
await page.getByLabel(/^Company \*$/).selectOption('co_alnoor')
await page.getByLabel('Email', { exact: true }).fill('sara@example.com')
await page.getByRole('button', { name: 'Add contact' }).last().click()
ok('contact added', await toast('Contact added'))
await page.getByLabel('Search contacts', { exact: true }).fill('Sara Test')
await page.getByText('Sara Test').first().click()
await page.waitForURL(/contacts\//)
await page.getByRole('button', { name: 'Log interaction' }).click()
await page.getByLabel('Event type', { exact: true }).selectOption('WhatsApp')
await page.getByLabel(/Description/).fill('Sent CV on WhatsApp')
await page.getByRole('button', { name: 'Log activity' }).click()
ok('interaction history shows entry', await page.getByText('Sent CV on WhatsApp').isVisible())

section('Global search / quick add / notifications')
await go('/')
await page.getByLabel(/Search companies, applications/).fill('hospitality')
ok('search hits applications + notes', (await page.getByRole('option').count()) >= 1)
await page.getByRole('option').first().click()
await page.waitForURL(u => u.pathname !== '/')
ok('search result navigates', /\/(applications|companies|contacts)\//.test(page.url()))
await page.keyboard.press('Control+k')
ok('Ctrl+K focuses search', await page.getByLabel(/Search companies, applications/).evaluate(e => e === document.activeElement))
for (const k of ['Company', 'Application', 'Contact', 'Interview', 'Follow-up', 'Activity']) {
  await page.getByRole('button', { name: 'Quick add' }).click()
  await page.getByRole('menuitem', { name: `+ ${k}` }).click()
  ok(`quick add: ${k} form opens`, await page.locator('dialog[open]').isVisible())
  await page.keyboard.press('Escape')
}
await page.getByRole('button', { name: /Notifications/ }).click()
ok('notifications list has interview + overdue', (await page.getByText(/Interview (today|tomorrow)/).count()) > 0 && (await page.getByText(/Follow-up overdue/).count()) > 0)
await page.getByRole('button', { name: 'Mark all read' }).click()
ok('mark all read clears badge', (await page.getByRole('button', { name: /^Notifications$/ }).count()) === 1)
await page.keyboard.press('Escape')

section('Calendar')
await go('/calendar')
for (const v of ['Week', 'Day', 'Agenda', 'Month']) { await page.getByRole('button', { name: v, exact: true }).click(); ok(`calendar ${v} view`, true) }
await page.getByRole('button', { name: 'Agenda', exact: true }).click()
ok('agenda lists upcoming events', (await page.getByText(/Follow up|Technical|Final/).count()) > 0)
await page.getByRole('button', { name: 'Next' }).click(); await page.getByRole('button', { name: 'Today' }).click()

section('Analytics')
await go('/analytics')
ok('KPI offer rate present', await page.getByText('Offer rate').isVisible())
ok('funnel has 5 steps', (await page.locator('[data-testid=funnel-step]').count()) === 5)
await page.locator('#range').selectOption('12')
ok('range switch', true)

section('Settings + persistence')
await go('/settings')
await page.getByLabel('Default currency').selectOption('EGP')
await page.getByLabel('Language & date format').selectOption('ar-EG')
await page.waitForTimeout(400)
await page.reload(); await page.waitForLoadState('networkidle')
ok('currency + locale persisted', (await page.getByLabel('Default currency').inputValue()) === 'EGP' && (await page.getByLabel('Language & date format').inputValue()) === 'ar-EG')
await page.getByLabel('Language & date format').selectOption('en-GB')
await page.getByLabel('Current password').fill('wrong-password')
await page.getByLabel('New password', { exact: true }).fill('new-password-1'); await page.getByLabel('Confirm new password').fill('new-password-1')
await page.getByRole('button', { name: 'Change password' }).click()
ok('wrong current password rejected', await toast('Current password is incorrect'))
await page.getByLabel('Current password').fill('correct-horse-9')
await page.getByRole('button', { name: 'Change password' }).click()
ok('password changed', await toast('Password changed'))
const [bk] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: /Full backup/ }).click()])
ok('JSON backup contains data', JSON.parse(fs.readFileSync(await bk.path(), 'utf8').replace(/^﻿/, '')).data.companies.length >= 13)

section('Sign out / in')
await page.getByRole('button', { name: 'Profile menu' }).click()
await page.getByRole('menuitem', { name: 'Sign out' }).click()
await page.getByLabel('Email').fill('me@example.com'); await page.getByLabel('Password').fill('bad-bad-bad')
await page.getByRole('button', { name: 'Sign in' }).click()
await page.getByText('Incorrect email or password').waitFor()
ok('bad login rejected', true)
await page.getByLabel('Password').fill('new-password-1')
await page.getByRole('button', { name: 'Sign in' }).click()
await page.getByRole('heading', { name: 'Settings' }).waitFor()
ok('login with new password', true)
const me = await ctx.request.get(base + '/api/bootstrap'); ok('API authed', me.ok())
const anon = await (await browser.newContext()).request.get(base + '/api/bootstrap'); ok('API rejects anonymous (401)', anon.status() === 401)

await browser.close()
console.log(`\n${pass} passed, ${fail} failed`)
if (errors.length) console.log('Runtime errors:\n' + errors.join('\n'))
process.exit(fail || errors.length ? 1 : 0)
